const pricingSchemas = [
  {
    _id: "ca3924d7-70ad-456c-9a46-67be6289f0e6",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "4-5",
    param1ValueOperator: "=",
    discount: "0",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "fc60ba90-90c2-4956-805d-683c2c273b84",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "6-7",
    param1ValueOperator: "=",
    discount: "4",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "d977d7c0-c7e8-4d70-9c4b-b77e1c500a8a",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "8-9",
    param1ValueOperator: "=",
    discount: "8",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "28765ce1-8ee8-40ab-92c4-e82935ac7abe",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "10-12",
    param1ValueOperator: "=",
    discount: "9",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "e67e74ff-4af9-4a01-a8d4-64af732240fd",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "13-24",
    param1ValueOperator: "=",
    discount: "10",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "3b99f234-16be-4797-8843-437c6b6f36b0",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "25-50",
    param1ValueOperator: "=",
    discount: "11",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "a2ff408f-1713-47b6-bd2c-f166ce3dfd73",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "51-75",
    param1ValueOperator: "=",
    discount: "13",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "63878e26-6023-40f5-a21d-ac45fb430f06",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "76-100",
    param1ValueOperator: "=",
    discount: "14",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "0a648cf5-6416-4186-96a5-a43d70e32126",
    param_2: " ",
    param2Value: "",
    param2ValueOperator: "",
    param_1: "HOURS",
    param1Value: "101-125",
    param1ValueOperator: "=",
    discount: "15",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "6-7",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "4",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "25-50",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "11",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "8-9",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "8",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "10-12",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "9",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "13-24",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "10",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "25-50",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "11",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "51-75",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "13",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "76-100",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "14",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    param_1: "HOURS",
    param_2: " ",
    param1Value: "101-125",
    param2Value: "",
    param1ValueOperator: "=",
    param2ValueOperator: "",
    discount: "15",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "454bf3ce-42ed-4b4e-801a-f2a58643e898",
    param_1: "HOURS",
    param_2: " ",
    param1Value: "126-150",
    param1ValueOperator: "=",
    param2Value: "",
    param2ValueOperator: "",
    discount: "16",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "22cd3d70-6c7d-4389-901d-c401c0732405",
    param_1: "HOURS",
    param_2: " ",
    param1Value: "151-200",
    param1ValueOperator: "=",
    param2Value: "",
    param2ValueOperator: "",
    discount: "17",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "f69444e4-0994-4f16-a314-a6e49a212c72",
    param_1: "HOURS",
    param_2: " ",
    param1Value: "201-260",
    param1ValueOperator: "=",
    param2Value: "",
    param2ValueOperator: "",
    discount: "18",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
  {
    _id: "5a671957-dd85-460f-9838-bdb7e6fdf346",
    param_1: "HOURS",
    param_2: " ",
    param1Value: "260",
    param1ValueOperator: ">",
    param2Value: "",
    param2ValueOperator: "",
    discount: "20",
    discountType: "FixedAMOUNT",
    clinicalCareRequired: false,
  },
];

function main() {
  const seenSchemas = new Map();
  const filteredSchemas = [];
  for (const priceSchema of pricingSchemas) {
    const schemaKey = `${priceSchema.param_1}-${priceSchema.param_2}-${priceSchema.param1Value}-${priceSchema.param2Value}-${priceSchema.param1ValueOperator}-${priceSchema.param2ValueOperator}-${priceSchema.discount}-${priceSchema.discountType}-${priceSchema.clinicalCareRequired}`;
    if (seenSchemas.get(schemaKey)) continue;
    seenSchemas.set(schemaKey, true);
    filteredSchemas.push(priceSchema);
  }
  console.log(filteredSchemas);
  console.log(filteredSchemas.length);
}

main();
